Support operate /data/adb/modules directory magisk.img was removed in the latest magisk canary build. The modules will be installed in the /data/adb/modules directory.
It is beneficial to do so. Of course we will follow it.

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -47,8 +47,13 @@ ABILONG=$(grep_prop ro.product.cpu.abi)
 
 # find magisk.img
 mountPath=/magisk
-[ -d /data/adb/magisk ] && IMG=/data/adb/magisk.img || IMG=/data/magisk.img
-[ ! -d /data/adb/magisk ] && [ ! -d /data/magisk ] && abort "Error: Please install or upgrade Magisk."
+if [ -d /data/adb/modules ]; then
+  migrated=true
+else
+  [ -d /data/adb/magisk ] && IMG=/data/adb/magisk.img || IMG=/data/magisk.img
+  [ ! -d /data/adb/magisk ] && [ ! -d /data/magisk ] && abort "Error: Please install or upgrade Magisk."
+  migrated=false
+fi
 
 rm -rf /tmp/mmr/
 mkdir -p /tmp/mmr/
@@ -57,8 +62,15 @@ unzip "${zipfile}"
 
 ui_print "Generating AROMA config"
 chmod 0755 ./script/*
-./script/mount-magisk.sh $IMG $mountPath || abort "Error: Failed to mount magisk.img!"
-./script/aroma-config-init.sh
+langs_dir=/tmp/mmr/template/META-INF/com/google/android/aroma/langs
+if $migrated; then
+  ./script/symlink-magisk.sh /data/adb/modules $mountPath
+  mv ${langs_dir}/en-2.lang ${langs_dir}/en.lang
+else
+  ./script/mount-magisk.sh $IMG $mountPath || abort "Error: Failed to mount magisk.img!"
+  mv ${langs_dir}/en-1.lang ${langs_dir}/en.lang
+fi
+./script/aroma-config-init.sh $mountPath
 
 cp -f ./script/aroma-config ./template/META-INF/com/google/android/
 chmod 0755 ./template/META-INF/com/google/android/aroma-config
